# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: waymo
  - model: smart_nano_1M
  - callbacks: default
  - logger: wandb
  - trainer: default
  - paths: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: camera_aware_smart # pre_bc, camera_aware_smart

action: fit # fit, finetune, validate, test

# task name, determines output directory path
task_name: "debug_open_source"

# simply provide checkpoint path to resume training
ckpt_path: null
train_log_dir: null

# seed for random number generators in pytorch, numpy and python.random
seed: 817

# Command line overrides
hydra:
  run:
    dir: ${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true
  verbose: true
